version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      python-production:
        dependency-type: production
        patterns: ["*"]
      python-development:
        dependency-type: development
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      web-production:
        dependency-type: production
        patterns: ["*"]
      web-development:
        dependency-type: development
        patterns: ["*"]
